### ISSUE TITLE
Todo 2

### ISSUE THREAD

**Issue by anthonytasca** [anthonytasca/pgrouting#24]
- [ ] Fix compilation warnings (https://travis-ci.org/cvvergara/pgrouting/jobs/325574762#L1674)
- [ ] Turn proof of concepts into pgtap tests
- [ ] Cleanup template comments (https://github.com/anthonytasca/pgrouting/blob/lineGraphFull/src/lineGraph/lineGraphFull.c#L31)

**Comment by anthonytasca** [comment]
split these into separate issues
